import type { Invoice, InvoiceStatus } from '../types';

export const INVOICE_STATUS_COLORS: Record<InvoiceStatus, string> = {
  Paid: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400',
  Partial: 'bg-orange-100 text-orange-700 dark:bg-orange-500/10 dark:text-orange-400',
  Draft: 'bg-slate-100 text-slate-700 dark:bg-slate-500/10 dark:text-slate-400',
  Pending: 'bg-red-100 text-red-700 dark:bg-red-500/10 dark:text-red-400',
  Unpaid: 'bg-red-100 text-red-700 dark:bg-red-500/10 dark:text-red-400',
};

export const MOCK_INVOICES: Invoice[] = [
  {
    "id": 9,
    "user_id": 2,
    "invoice_number": "0009",
    "invoice_date": "2026-04-15T14:00:00.000000Z",
    "created_at": "2026-04-16T05:00:34.000000Z",
    "amount": "0.00",
    "amount_paid": "0.00",
    "status": "Paid",
    "zoho_invoice_number": null,
    "send_email": "no",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 1,
    "credit_amount": "0.00",
    "user": {
      "name": "Customer1 User",
      "email": "customer1@example.com"
    },
    "balance": "0.00",
    "till_date_paid": "0.00",
    "is_custom": 0,
    "can_remind": false,
    "reminder_reason": "Send the invoice before reminding."
  },
  {
    "id": 8,
    "user_id": 7,
    "invoice_number": "0008",
    "invoice_date": "2026-02-27T13:00:00.000000Z",
    "created_at": "2026-02-28T04:54:52.000000Z",
    "amount": "740.00",
    "amount_paid": "0.00",
    "status": "Draft",
    "zoho_invoice_number": null,
    "send_email": "yes",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 0,
    "credit_amount": "0.00",
    "user": {
      "name": "Shikhar Test",
      "email": "shikhar+5@digisite.com.au"
    },
    "balance": "740.00",
    "till_date_paid": "0.00",
    "is_custom": 1,
    "can_remind": false,
    "reminder_reason": "Reminders available for sent/unpaid/partial invoices only."
  },
  {
    "id": 7,
    "user_id": 7,
    "invoice_number": "0007",
    "invoice_date": "2026-02-27T13:00:00.000000Z",
    "created_at": "2026-02-27T22:51:52.000000Z",
    "amount": "900.00",
    "amount_paid": "650.00",
    "status": "Partial",
    "zoho_invoice_number": null,
    "send_email": "yes",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 0,
    "credit_amount": "0.00",
    "user": {
      "name": "Shikhar Test",
      "email": "shikhar+5@digisite.com.au"
    },
    "balance": "250.00",
    "till_date_paid": "650.00",
    "is_custom": 1,
    "can_remind": true,
    "reminder_reason": ""
  },
  {
    "id": 6,
    "user_id": 7,
    "invoice_number": "0006",
    "invoice_date": "2026-02-26T13:00:00.000000Z",
    "created_at": "2026-02-27T07:12:48.000000Z",
    "amount": "800.00",
    "amount_paid": "800.00",
    "status": "Paid",
    "zoho_invoice_number": null,
    "send_email": "no",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 0,
    "credit_amount": "0.00",
    "user": {
      "name": "Shikhar Test",
      "email": "shikhar+5@digisite.com.au"
    },
    "balance": "0.00",
    "till_date_paid": "800.00",
    "is_custom": 1,
    "can_remind": false,
    "reminder_reason": "Send the invoice before reminding."
  },
  {
    "id": 5,
    "user_id": 23,
    "invoice_number": "0005",
    "invoice_date": "2026-02-26T13:00:00.000000Z",
    "created_at": "2026-02-27T06:28:34.000000Z",
    "amount": "300.00",
    "amount_paid": "0.00",
    "status": "Draft",
    "zoho_invoice_number": null,
    "send_email": "no",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 0,
    "credit_amount": "0.00",
    "user": {
      "name": "Chirag Test",
      "email": "chirag.gondaliya03@gmail.com"
    },
    "balance": "300.00",
    "till_date_paid": "0.00",
    "is_custom": 1,
    "can_remind": false,
    "reminder_reason": "Send the invoice before reminding."
  },
  {
    "id": 4,
    "user_id": 9,
    "invoice_number": "0004",
    "invoice_date": "2026-02-19T13:00:00.000000Z",
    "created_at": "2026-02-24T06:14:26.000000Z",
    "amount": "901.36",
    "amount_paid": "50.00",
    "status": "Partial",
    "zoho_invoice_number": null,
    "send_email": "yes",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 1,
    "credit_amount": "0.00",
    "user": {
      "name": "Chirag 10 Gondaliya 10",
      "email": "chirag.magecurious@gmail.com"
    },
    "balance": "851.36",
    "till_date_paid": "50.00",
    "is_custom": 0,
    "can_remind": true,
    "reminder_reason": ""
  },
  {
    "id": 3,
    "user_id": 9,
    "invoice_number": "0003",
    "invoice_date": "2025-12-30T13:00:00.000000Z",
    "created_at": "2025-12-30T13:07:59.000000Z",
    "amount": "100.00",
    "amount_paid": "50.00",
    "status": "Partial",
    "zoho_invoice_number": null,
    "send_email": "no",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 0,
    "credit_amount": "0.00",
    "user": {
      "name": "Chirag 10 Gondaliya 10",
      "email": "chirag.magecurious@gmail.com"
    },
    "balance": "50.00",
    "till_date_paid": "50.00",
    "is_custom": 1,
    "can_remind": false,
    "reminder_reason": "Send the invoice before reminding."
  },
  {
    "id": 2,
    "user_id": 2,
    "invoice_number": "0002",
    "invoice_date": "2025-12-29T13:00:00.000000Z",
    "created_at": "2025-12-30T07:22:13.000000Z",
    "amount": "122.10",
    "amount_paid": "0.00",
    "status": "Unpaid",
    "zoho_invoice_number": null,
    "send_email": "no",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 0,
    "credit_amount": "0.00",
    "user": {
      "name": "Customer1 User",
      "email": "customer1@example.com"
    },
    "balance": "122.10",
    "till_date_paid": "0.00",
    "is_custom": 1,
    "can_remind": false,
    "reminder_reason": "Send the invoice before reminding."
  },
  {
    "id": 1,
    "user_id": 7,
    "invoice_number": "0001",
    "invoice_date": "2025-12-29T13:00:00.000000Z",
    "created_at": "2025-12-30T02:29:30.000000Z",
    "amount": "85.00",
    "amount_paid": "11.00",
    "status": "Partial",
    "zoho_invoice_number": null,
    "send_email": "yes",
    "reminder_count": 0,
    "last_reminder_sent_at": null,
    "has_linked_orders": 0,
    "credit_amount": "0.00",
    "user": {
      "name": "Shikhar Test",
      "email": "shikhar+5@digisite.com.au"
    },
    "balance": "74.00",
    "till_date_paid": "11.00",
    "is_custom": 1,
    "can_remind": true,
    "reminder_reason": ""
  }
];

export const INVOICE_COLUMN_CONFIG = [
  { key: 'invoice_number', header: 'INVOICE #' },
  { key: 'zoho_invoice_number', header: 'ZOHO INVOICE #' },
  { key: 'status', header: 'STATUS' },
  { key: 'customer', header: 'CUSTOMER' },
  { key: 'total', header: 'TOTAL' },
  { key: 'issued_date', header: 'ISSUED DATE' },
  { key: 'till_date_paid', header: 'TILL DATE PAID' },
  { key: 'remaining_balance', header: 'REMAINING BALANCE' },
  { key: 'action', header: 'ACTION' },
];
