export const API_ENDPOINTS = {
    AUTH: {
        ADMIN_LOGIN: "/admin/auth/login",
        CUSTOMER_LOGIN: "/customer/auth/login",
        REGISTER: "/customer/auth/register",
        FORGOT_PASSWORD: "/customer/auth/forgot-password",
        RESEND_VERIFICATION: "/customer/auth/email/resend",
        VERIFICATION_STATUS: "/customer/auth/verification-status",
        VERIFY_EMAIL: "/customer/auth/verify-email",
        EMAIL_VERIFY: (customerId: string | number, token: string) => `/customer/auth/email/verify/${customerId}/${token}`,
        ONBOARDING: "/customer/onboarding",
        LOGOUT: "/auth/logout",
        USER_DETAILS: "/auth/me",
        RESET_PASSWORD: "/customer/auth/reset-password",
        ACCEPT_TERMS: "/customer/auth/accept-terms",
    },
    ORDERS: {
        LIST: "/orders",
        CREATE: "/orders",
        UPDATE: (orderId: string | number) => `/orders/${orderId}`,
        DETAILS: (id: string | number) => `/orders/${id}`,
        CANCEL: (id: string | number) => `/orders/${id}/cancel`,
        CONSIGN: (id: string | number, isAdmin: boolean = false) => isAdmin ? `/admin/orders/${id}/consign` : `/customer/orders/${id}/consign`,
        LABEL_DOWNLOAD: (id: string | number) => `/orders/${id}/label/download`,

        COUNTS: "/orders/counts",
        PAYMENT_INFO: (id: string | number) => `/customer/orders/${id}/payment`,
        PAY_WITH_WALLET: (id: string | number) => `/customer/orders/${id}/pay-with-wallet`,
        WALLET_CHECK: "/customer/orders/wallet-check",
        ADMIN_WALLET_CHECK: "/admin/wallet/check",
        IMPORT: "/orders/import",
        EXPORT: "/orders/export",
        CREATE_OWN_COURIER: "/orders/create-own-courier",
        GET_QUOTE_SERVICES: "/customer/get-quote/services",
        RECEIVER_ADDRESS: (id: string | number) => `/customer/orders/${id}/receiver-address`,
        IMPORT_SAMPLE: "/customer/orders/import/sample",
        ARCHIVE: (id: string | number) => `/orders/${id}/archive`,
        MASS_CANCEL: "/orders/mass-cancel",
        MASS_ARCHIVE: "/orders/mass-archive",
        RESTORE: (orderNumber: string | number) => `/admin/orders/${orderNumber}/restore`,
        PRINT_ORDER: "/orders/print-label",
        PACKING_SLIP: "/orders/packing-slip",
        PACKING_SUMMARY: "/orders/packing-summary",
        UPDATE_COURIER: (orderNumber: string) => `/orders/${orderNumber}/courier`,
        AUSPOST_MANIFEST: "/customer/orders/auspost/manifests",
        MANUAL_STORE: "/admin/orders/manual-store",
        ADD_MANUAL_TRACKING_NUMBERS: (orderNumber: string) => `/admin/orders/${orderNumber}/tracking`,
        PRINT_LABELS_CHECK: "/orders/print-labels/check",
        PRINT_LABELS: "/orders/print-labels",
        PRINT_LABELS_STATUS: (printId: string) => `/orders/print-labels/${printId}`,
        PRINT_LABELS_FILE: (printId: string) => `/orders/print-labels/${printId}/file`,
        VALIDATE_ADDRESSES_APPLY: "/orders/validate-addresses/apply",
        // Legacy batch-history URLs (kept for any leftover callers).
        BULK_PRINT: "/orders/bulk-print",
        BULK_PRINT_DETAILS: (batchId: string) => `/orders/bulk-print/${batchId}`,
        BULK_PRINT_LABELS: (batchId: string) => `/orders/bulk-print/${batchId}/labels`,
    },
    // Unauthenticated: served without the role prefix the shared api client adds.
    // Takes either an order_number or a tracking_number as a query parameter.
    PUBLIC_TRACKING: {
        SEARCH: "/tracking",
    },
    // Authenticated customer branding for the public tracking page.
    TRACKING_PAGE: {
        SETTINGS: "/tracking-page/settings",
    },
    DASHBOARD: {
        METRICS: "/dashboard/metrics",
    },
    ITEMS: {
        BASE: "/items",
        EXPORT: "/items/export",
    },
    ADDRESS_BOOK: {
        BASE: "/customer/address-book",
        EXPORT: "/customer/address-book/export",
        SEARCH: "/customer/address-book/search",
    },
    REPORTS: {
        SHIPMENT: "/customer/report/shipment",
        SHIPMENT_EXPORT: "/customer/report/shipment/export",
        TRANSACTION: "/customer/report/transection",
        TRANSACTION_EXPORT: "/customer/report/transection/export",
        INVOICE: "/customer/report/invoice",
        PARCELS: "/customer/report/parcels",
        PARCELS_EXPORT: "/customer/report/parcels/export",
        COUNTS: "/customer/report/counts",
    },
    INVOICES: {
        BASE: "/customer/invoices",
        EXPORT: "/customer/invoices/export",
        DOWNLOAD: (id: string | number) => `/customer/invoices/${id}/download`,
    },
    ADMIN_INVOICES: {
        BASE: "/admin/customer-invoice-management",
        DETAILS: (id: string | number) => `/admin/customer-invoice-management/${id}`,
        SEND: (id: string | number) => `/admin/customer-invoice-management/${id}/send`,
        DOWNLOAD: (id: string | number) => `/admin/customer-invoice-management/${id}/download`,
        REMIND: (id: string | number) => `/admin/customer-invoice-management/${id}/remind`,
        PAYMENTS: (id: string | number) => `/admin/customer-invoice-management/${id}/payments`,
        PAYMENT_DETAILS: (invoiceId: string | number, paymentId: string | number) => `/admin/customer-invoice-management/${invoiceId}/payments/${paymentId}`,
        EXPORT: "/admin/customer-invoice-management/export",
    },
    ENQUIRIES: {
        BASE: "/customer/enquiries",
    },
    CUSTOMER_BOOK_PICKUP: {
        BASE: "/customer/book-pickup",
    },
    HELP_CENTER: {
        LIST: "/customer/help-center",
        DETAILS: (slug: string) => `/customer/help-center/${slug}`,
    },
    ADMIN_CUSTOMERS: {
        BASE: "/admin/customers",
        COUNTS: "/admin/customers/counts",
        DETAILS: (id: string | number) => `/admin/customers/${id}`,
        EDIT: (id: string | number) => `/admin/customers/${id}/edit`,
        PROFILE: (id: string | number) => `/admin/customers/${id}/profile`,
        ORDERS: (id: string | number) => `/admin/customers/${id}/orders`,
        TRANSACTION: (id: string | number) => `/admin/customers/${id}/transaction`,
        INVOICE: (id: string | number) => `/admin/customers/${id}/invoice`,
        VERIFY: (id: string | number) => `/admin/customers/${id}/verify`,
        TOGGLE_STATUS: (id: string | number) => `/admin/customers/${id}/toggle-status`,
        ACCOUNT_ACTIVATION: (id: string | number) => `/admin/customers/${id}/toggle-account-activation`,
        EXPORT: "/admin/customers/export",
        ORDERS_EXPORT: (id: string | number) => `/admin/customers/${id}/orders/export`,
        TRANSACTION_EXPORT: (id: string | number) => `/admin/customers/${id}/transaction/export`,
        INVOICE_EXPORT: (id: string | number) => `/admin/customers/${id}/invoice/export`,
        INTEGRATIONS: (id: string | number) => `/admin/customers/${id}/integrations`,
        ITEMS: (id: string | number) => `/admin/customers/${id}/items`,
        WALLET_TOP_UP: "/admin/wallet/top-up",
        CHANGE_PASSWORD: (id: string | number) => `/admin/customers/${id}/change-password`,
        ME: (id: string | number) => `/admin/customers/${id}/me`,
    },
    ADMIN_STAFF: {
        BASE: "/admin/staff",
        FORM_OPTIONS: "/admin/staff/form-options",
        COUNTS: "/admin/staff/counts",
        EXPORT: "/admin/staff/export",
        DETAILS: (id: string | number) => `/admin/staff/${id}`,
        TOGGLE_STATUS: (id: string | number) => `/admin/staff/${id}/toggle-status`,
    },
    ADMIN_ACTIVITIES: {
        BASE: "/admin/activities",
    },
    ADMIN_BOOK_PICKUP: {
        BASE: "/admin/book-pickup",
        COUNTS: "/admin/book-pickup/counts",
        EXPORT: "/admin/book-pickup/export",
    },
    ADMIN_COURIER_POSTCODES: {
        BASE: "/admin/courier-postcodes",
        DETAILS: (id: string | number) => `/admin/courier-postcodes/${id}`,
        EXPORT: "/admin/courier-postcodes/export",
    },
    ADMIN_QUOTES: {
        BASE: "/admin/quotes",
        DETAILS: (id: string | number) => `/admin/quotes/${id}`,
        SERVICES: "/quotes/services",
        EXPORT: "/admin/quotes/export",
    },
    CUSTOMER_QUOTES: {
        SERVICES: "/get-quote/services",
        LOCALITIES_SEARCH: "/localities/search",
    },
    LOCALITIES: {
        VALIDATE: "/localities/validate",
    },
    ADMIN_COURIER_SURCHARGES: {
        BASE: "/admin/courier-surcharges",
        DETAILS: (id: string | number) => `/admin/courier-surcharges/${id}`,
        GLOBAL_COURIERS: "/admin/courier-surcharges/global-couriers",
        EXPORT: "/admin/courier-surcharges/export",
    },
    ADMIN_CANCEL_ORDERS: {
        BASE: "/admin/cancel-orders",
        COUNTS: "/admin/cancel-orders/counts",
        EXPORT: "/admin/cancel-orders/export",
    },
    ADMIN_REPORTS: {
        PARCELS: "/admin/reports/customer-parcels",
        PARCELS_EXPORT: "/admin/reports/customer-parcels/export",
        INTEGRATED_PARCELS: "/admin/reports/integrated-courier-parcels",
        INTEGRATED_PARCELS_EXPORT: "/admin/reports/integrated-courier-parcels/export",
        ALL_PARCELS: "/admin/reports/all-parcels",
        ALL_PARCELS_EXPORT: "/admin/reports/all-parcels/export",
        AUSPOST_ORDER_SUMMARY: "/admin/reports/auspost-order-summary",
        AUSPOST_ORDER_SUMMARY_EXPORT: "/admin/reports/auspost-order-summary/export",
        UNDELIVERED_PARCELS: "/admin/reports/undelivered-parcels",
        UNDELIVERED_PARCELS_EXPORT: "/admin/reports/undelivered-parcels/export",
        DIRECT_FREIGHT_UPLOAD: "/admin/reports/customer-parcels/direct-freight-upload",
        AUSPOST_UPLOAD: "/admin/reports/customer-parcels/auspost-upload",
        AUSPOST: "/admin/reports/auspost",
        AUSPOST_EXPORT: "/admin/reports/auspost/export",
        ORDER_LABEL_CHARGES: "/admin/reports/order-label-charges",
        ORDER_LABEL_CHARGES_EXPORT: "/admin/reports/order-label-charges/export",
    },
    ADMIN_HELP_CENTER: {
        BASE: "/admin/help-center/articles",
        DETAILS: (id: string | number) => `/admin/help-center/articles/${id}`,
    },
    ADMIN_SETTINGS: {
        BASE: "/admin/settings",
        DETAILS: (id: string | number) => `/admin/settings/${id}`,
    },
    ANNOUNCEMENTS: {
        BASE: "/admin/announcements",
        DETAILS: (id: string | number) => `/admin/announcements/${id}`,
    },
    BLACKOUT_DAYS: {
        BASE: "/admin/blackout-days",
        DETAILS: (id: string | number) => `/admin/blackout-days/${id}`,
    },
    SEARCH: {
        GLOBAL: "/globalsearch",
    },
    XERO: {
        CONNECT: "/admin/xero/connect",
        STATUS: "/admin/xero/status",
        DISCONNECT: "/admin/xero/disconnect",
        CONTACTS: "/admin/xero/contacts",
        SYNC_INVOICE: (id: string | number) => `/admin/xero/invoices/${id}/sync`,
    },
    PROFILE: {
        GET: "/profile",
        UPDATE: "/profile",
        CHANGE_PASSWORD: "/profile/change-password",
    },
    WALLET: {
        SUMMARY: "/customer/wallet",
        RECEIPT: (transactionId: string | number) => `/customer/wallet/transactions/${transactionId}/receipt`,
    },
    INTEGRATIONS: {
        BASE: "/integrations",
        DETAILS: (provider: string) => `/integrations/${provider}`,
        CONNECT: (provider: string) => `/integrations/${provider}/connect`,
        DISCONNECT: (provider: string) => `/integrations/${provider}/disconnect`,
        SYNC: (provider: string) => `/integrations/${provider}/sync`,
        AUTO_FULFILLMENT: "/integrations/shopify/auto-fulfillment",
        SHOPIFY_LIVE_RATES: "/integrations/shopify/live-rates",
        SHOPIFY_LIVE_RATES_SETTINGS: "/integrations/shopify/live-rates/settings",
        SHOPIFY_PARCEL_DEFAULTS: "/integrations/shopify/package-defaults",
        // Note the extra `customer` segment: these do not sit under /integrations like the rest.
        SHOPIFY_SHIPPING_METHODS: "/customer/integrations/shopify/shipping-methods",
        SHOPIFY_SHIPPING_METHOD: (id: string) => `/customer/integrations/shopify/shipping-methods/${id}`,
        SHOPLINE_PARCEL_DEFAULTS: "/integrations/shopline/package-defaults",
        SAVE_WOOCOMMERCE: "/integrations/woocommerce/save",
        PRODUCTS_STATUS: (provider: string) => `/integrations/${provider}/products/status`,
        ADVANCED_SETTINGS: (provider: string) => `/integrations/${provider}/advanced-settings`,
        PRODUCTS: (provider: string) => `/integrations/${provider}/products`,
        MANUAL_PRODUCT_DETAILS: (provider: string, productCode: string) => `/integrations/${provider}/products/${productCode}`,
        PATCH_PRODUCT_STATUS: (provider: string, productCode: string) => `/integrations/${provider}/products/${productCode}/status`,
        DEFAULT: (provider: string) => `/integrations/${provider}/default`,
        EBAY_AUTO_SYNC: "/integrations/ebay/auto-sync",
        EBAY_AUTO_FULFILLMENT: "/integrations/ebay/auto-fulfillment",
        SQUARESPACE_AUTO_FULFILLMENT: "/integrations/squarespace/auto-fulfillment",
        SHOPLINE_AUTO_SYNC: "/integrations/shopline/auto-sync",
        SHOPLINE_AUTO_FULFILLMENT: "/integrations/shopline/auto-fulfillment",
        ETSY_AUTO_SYNC: "/integrations/etsy/auto-sync",
        ETSY_AUTO_FULFILLMENT: "/integrations/etsy/auto-fulfillment",
    },
    PLAN: {
        SELECT: "/customer/plans/select"
    },
    MANIFEST: {
        LIST: "/customer/orders/auspost/manifests",
        EXPORT: "/customer/orders/auspost/manifests/export",
    },
    CUSTOMER_TEAM: {
        BASE: "/customer/team-users",
        FORM_OPTIONS: "/customer/team-users/form-options",
        DETAILS: (id: string | number) => `/customer/team-users/${id}`,
        TOGGLE_STATUS: (id: string | number) => `/customer/team-users/${id}/toggle-status`,
    },
    RULES: {
        BASE: "/customer/rule-management",
        OPTIONS: "/customer/rule-management/options",
        REORDER: "/customer/rule-management/reorder",
        RUN: "/customer/rule-management/run",
        RUN_STATUS: "/customer/rule-management/run-status",
        DETAILS: (id: string | number) => `/customer/rule-management/${id}`,
    },
    PACKING_SLIP_SETTINGS: {
        BASE: "/customer/packing-slip-settings",
        SAMPLE: "/customer/packing-slip-settings/sample",
        SORTING: "/customer/packing-slip-settings/sorting",
        SUMMARY: "/customer/packing-slip-settings/summary",
        SUMMARY_SAMPLE: "/customer/packing-slip-settings/summary/sample",
    },
    ADMIN_DEBUG_CENTRE: {
        BASE: "/admin/debug-centre",
        STATS: "/admin/debug-centre/counts",
        TRACES: "/admin/debug-centre/traces",
        ALERTS: "/admin/debug-centre/alerts",
        FAILED_JOBS: "/admin/debug-centre/failed-jobs",
        EXTERNAL_API_FAILURES: "/admin/debug-centre/external-api-failures",
        SLOW_REQUESTS: "/admin/debug-centre/slow-requests",
        SLOW_EXTERNAL_CALLS: "/admin/debug-centre/slow-external-calls",
        CUSTOMER_ACTIVITY: "/admin/debug-centre/customer-activity",
        TRACE_DETAIL: (id: string | number) => `/admin/debug-centre/traces/${id}`,
    }
};

export const QUERY_KEYS = {
    AUTH: {
        VERIFICATION_STATUS: ["auth", "verification-status"],
        USER_DETAILS: ["auth", "user-details"],
    },
    ORDERS: {
        LIST: ["orders", "list"],
        DETAILS: (id: string | number) => ["orders", "details", id],
        PAYMENT_INFO: (id: string | number) => ["orders", "payment", id],
        COUNTS: (customer?: string | number) => ["orders", "counts", customer || "all"],
        RECEIVER_ADDRESS: (id: string | number) => ["orders", "receiver-address", id],
        PRINT_LABELS_STATUS: (printId: string) => ["orders", "print-labels", printId],
        BULK_PRINT_LIST: ["orders", "bulk-print", "list"],
        BULK_PRINT_DETAILS: (batchId: string) => ["orders", "bulk-print", "details", batchId],
    },
    PUBLIC_TRACKING: (method: string, value: string) => ["public-tracking", method, value],
    TRACKING_PAGE_SETTINGS: ["tracking-page", "settings"],
    DASHBOARD: {
        METRICS: ["dashboard", "metrics"],
    },
    ITEMS: {
        LIST: ["items", "list"],
        DETAILS: (id: number | string) => ["items", "details", id],
        DEFAULT: ["items", "default"],
    },
    ADDRESS_BOOK: {
        LIST: ["address-book", "list"],
        DETAILS: (id: number | string) => ["address-book", "details", id],
        SEARCH: (q: string) => ["address-book", "search", q],
    },
    REPORTS: {
        SHIPMENT: ["reports", "shipment"],
        TRANSACTION: ["reports", "transaction"],
        INVOICE: ["reports", "invoice"],
        PARCELS: ["reports", "parcels"],
        ALL_PARCELS: ["reports", "all-parcels"],
        AUSPOST_SUMMARY: ["reports", "auspost-summary"],
        AUSPOST_REPORT: ["reports", "auspost-report"],
        UNDELIVERED_PARCELS: ["reports", "undelivered-parcels"],
        COUNTS: ["reports", "counts"],
        ORDER_LABEL_CHARGES: ["reports", "order-label-charges"],
    },
    ADMIN_HELP_CENTER: {
        LIST: ["admin", "help-center", "list"],
        DETAILS: (id: string | number) => ["admin", "help-center", "details", id],
    },
    INVOICES: {
        LIST: ["invoices", "list"],
        DETAILS: (id: number | string) => ["invoices", "details", id],
    },
    HELP_CENTER: {
        LIST: ["help-center", "list"],
        DETAILS: (slug: string) => ["help-center", "details", slug],
    },
    ADMIN_CUSTOMERS: {
        LIST: ["admin", "customers", "list"],
        COUNTS: ["admin", "customers", "counts"],
        DETAILS: (id: string | number) => ["admin", "customers", "details", id],
        PROFILE: (id: string | number) => ["admin", "customers", "profile", id],
        ORDERS: (id: string | number) => ["admin", "customers", "orders", id],
        TRANSACTION: (id: string | number) => ["admin", "customers", "transaction", id],
        INVOICE: (id: string | number) => ["admin", "customers", "invoice", id],
        INTEGRATIONS: (id: string | number) => ["admin", "customers", "integrations", id],
        ITEMS: (id: string | number) => ["admin", "customers", "items", id],
        ME: (id: string | number) => ["admin", "customers", "me", id],
    },
    ADMIN_STAFF: {
        LIST: ["admin", "staff", "list"],
        FORM_OPTIONS: ["admin", "staff", "form-options"],
        COUNTS: ["admin", "staff", "counts"],
        DETAILS: (id: string | number) => ["admin", "staff", "details", id],
    },
    ADMIN_ACTIVITIES: {
        LIST: ["admin", "activities", "list"],
    },
    ADMIN_BOOK_PICKUP: {
        LIST: ["admin", "book-pickup", "list"],
        COUNTS: ["admin", "book-pickup", "counts"],
    },
    ADMIN_COURIER_POSTCODES: {
        LIST: ["admin", "courier-postcodes", "list"],
        DETAILS: (id: string | number) => ["admin", "courier-postcodes", "details", id],
    },
    ADMIN_QUOTES: {
        LIST: ["admin", "quotes", "list"],
        DETAILS: (id: string | number) => ["admin", "quotes", "details", id],
    },
    ADMIN_COURIER_SURCHARGES: {
        GLOBAL_COURIERS: ["admin", "courier-surcharges", "global-couriers"],
    },
    ADMIN_CANCEL_ORDERS: {
        LIST: ["admin", "cancel-orders", "list"],
        COUNTS: ["admin", "cancel-orders", "counts"],
    },
    ADMIN_SETTINGS: {
        LIST: ["admin", "settings", "list"],
        DETAILS: (slug: string) => ["admin", "settings", "details", slug],
    },
    ANNOUNCEMENTS: {
        LIST: ["admin", "announcements", "list"],
        DETAILS: (id: string | number) => ["admin", "announcements", "details", id],
    },
    BLACKOUT_DAYS: {
        LIST: ["admin", "blackout-days", "list"],
        DETAILS: (id: string | number) => ["admin", "blackout-days", "details", id],
    },
    SEARCH: {
        GLOBAL: (q: string) => ["search", "global", q],
    },
    WALLET: {
        SUMMARY: ["wallet", "summary"],
    },
    LOCALITIES: {
        SEARCH: (q: string) => ["localities", "search", q],
        VALIDATE: (suburb: string, state: string, postcode: string, address: string) => ["localities", "validate", suburb, state, postcode, address],
    },
    INTEGRATIONS: {
        LIST: ["integrations"],
        STATUS: (provider: string) => ["integration-status", provider],
        SHOPIFY_LIVE_RATES_SETTINGS: (storeId: string | number) => ["shopify-live-rates-settings", storeId],
        MANUAL_PRODUCTS: (provider: string) => ["manual-products", provider],
    },
    MANIFEST: {
        LIST: ["manifests", "list"],
        DETAILS: (id: string | number) => ["manifests", "details", id],
    },
    CUSTOMER_TEAM: {
        LIST: ["customer", "team-users", "list"],
        FORM_OPTIONS: ["customer", "team-users", "form-options"],
        DETAILS: (id: string | number) => ["customer", "team-users", "details", id],
    },
    ENQUIRIES: {
        LIST: ["enquiries", "list"],
    },
    RULES: {
        LIST: ["rules", "list"],
        DETAILS: (id: string | number) => ["rules", "details", id],
        OPTIONS: ["rules", "options"],
        RUN_STATUS: ["rules", "run-status"],
    },
    PACKING_DOCUMENTS: {
        SLIP_SETTINGS: ["settings", "packing-slip"],
        SUMMARY_SETTINGS: ["settings", "packing-summary"],
        SORTING: ["settings", "packing-sorting"],
    },
    XERO: {
        STATUS: ["admin", "xero", "status"],
        CONTACTS: (xeroContactId?: string) => ["admin", "xero", "contacts", xeroContactId || "all"],
    },
    ADMIN_DEBUG_CENTRE: {
        STATS: ["admin", "debug-centre", "stats"],
        TRACES: ["admin", "debug-centre", "traces"],
        ALERTS: ["admin", "debug-centre", "alerts"],
        FAILED_JOBS: ["admin", "debug-centre", "failed-jobs"],
        EXTERNAL_API_FAILURES: ["admin", "debug-centre", "external-api-failures"],
        SLOW_REQUESTS: ["admin", "debug-centre", "slow-requests"],
        SLOW_EXTERNAL_CALLS: ["admin", "debug-centre", "slow-external-calls"],
        CUSTOMER_ACTIVITY: ["admin", "debug-centre", "customer-activity"],
        TRACE_DETAIL: (id: string | number) => ["admin", "debug-centre", "trace", id],
    }
};