export const AUSTRALIAN_STATES = [
  { label: 'ACT', value: 'ACT' },
  { label: 'NSW', value: 'NSW' },
  { label: 'NT', value: 'NT' },
  { label: 'QLD', value: 'QLD' },
  { label: 'SA', value: 'SA' },
  { label: 'TAS', value: 'TAS' },
  { label: 'VIC', value: 'VIC' },
  { label: 'WA', value: 'WA' },
];

export const STREET_TYPES = [
  { label: 'Alley', value: 'Alley' },
  { label: 'Avenue', value: 'Avenue' },
  { label: 'Boulevard', value: 'Boulevard' },
  { label: 'Byway', value: 'Byway' },
  { label: 'Close', value: 'Close' },
  { label: 'Circuit', value: 'Circuit' },
  { label: 'Crescent', value: 'Crescent' },
  { label: 'Court', value: 'Court' },
  { label: 'Cove', value: 'Cove' },
  { label: 'Drive', value: 'Drive' },
  { label: 'Esplanade', value: 'Esplanade' },
  { label: 'Grove', value: 'Grove' },
  { label: 'Heights', value: 'Heights' },
  { label: 'Highway', value: 'Highway' },
  { label: 'Lane', value: 'Lane' },
  { label: 'Lookout', value: 'Lookout' },
  { label: 'Lower', value: 'Lower' },
  { label: 'Meadow', value: 'Meadow' },
  { label: 'Parade', value: 'Parade' },
  { label: 'Place', value: 'Place' },
  { label: 'Road', value: 'Road' },
  { label: 'Square', value: 'Square' },
  { label: 'Street', value: 'Street' },
  { label: 'Terrace', value: 'Terrace' },
  { label: 'Town', value: 'Town' },
  { label: 'Towers', value: 'Towers' },
  { label: 'Upper', value: 'Upper' },
  { label: 'View', value: 'View' },
  { label: 'Walk', value: 'Walk' },
  { label: 'Way', value: 'Way' },
];
